### ISSUE TITLE
ENOENT: no such file or directory, open '.phrase.yml'

### ISSUE THREAD

**Issue by FDiskas** [blabu-com/phrase-tools#1]
Latest and greatest phrase projects has different file name `.phraseapp.yml` and syntax

https://github.com/blabu-com/phrase-tools/blob/08b9fa82af94af2513845a6366db573e03a691a0/src/prune.ts#L9

**Comment by Poky85** [comment]
`.phraseapp.yml` was config used in CLI v1. Here is the migration guide for version 2 https://help.phrase.com/help/migration-guide-phrase-cli-v1-to-v2
